services:
  bot:
    build: .
    restart: always
    depends_on:
      - mongo
    env_file:
      - .env
    networks:
      - mongo-network

  mongo:
    image: mongo:4.4.7
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - mongo-network
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db

volumes:
  db:

networks:
  mongo-network:
    driver: bridge